(defun solve (n cost)
  (let ((done (make-array 10 :initial-element nil))
        (donenum 0)
        (m 0))
    (loop while (< donenum 10)
          for mm = (loop for x across ()))))

(let* ((h (read))
       (w (read))
       (c (make-array '(10 10)))
       (a (make-array `(,h ,w))))
  (dotimes (i 10)
    (dotimes (j 10)
      (setf (aref c i j)
            (read))))
  (dotimes (i h)
    (dotimes (j w)
      (setf (aref a i j)
            (read))))
  )
