(let* ((n (read-line))
      (a (char-code (char n 0)))
      (b (char-code (char n 1)))
      (c (char-code (char n 2)))
      (d (char-code (char n 3))))
  (if (or (= a b c)
          (= b c d))
      (format t "Yes~%")
      (format t "No~%")))
