(let* ((n (read))
       (a (make-array n))
       (one 0)
       (four 0)
       (two 0))
  (dotimes (i n)
    (let ((ai (read)))
      (if (zerop (mod ai 4))
	  (incf four)
	  (if (zerop (mod ai 2))
	      (incf two)
	      (incf one)))
      (setf (aref a i) ai)))
  (format t "~A~%"
	  (if (zerop two)
	      (if (<= one (1+ four)) "Yes" "No")
	      (if (<= one four) "Yes" "No"))))
