(let* ((n (read))
       (a (make-array n :element-type 'integer))
       (x 0)
       (y 0)
       (res 0))
  (dotimes (i n)
    (setf (aref a i) (read)))
  (setf x (aref a 0)
        y (loop for i from 1 below n sum (aref a i))
        res (abs (- x y)))
  (loop for i from 1 below (1- n)
        for ai = (aref a i) do
        (incf x ai)
        (decf y ai)
        (setf res (min res (abs (- x y)))))
  (format t "~A~%" res))
