(let* ((a (read))
       (b (read))
       (zp (or (and (minusp a) (plusp b))
               (zerop a)
               (zerop b)))
       (nm (if (minusp a)
               (if (minusp b)
                   (abs (- b a))
                   (abs a))
               0)))
  (format t "~A~%"
    (cond
      (zp "Zero")
      ((or (zerop nm)
           (and (minusp a) (oddp nm))
           (and (plusp a) (evenp nm)))
       "Positive")
      ((or (and (minusp a) (evenp nm))
           (and (plusp a) (oddp nm))) "Negative"))))
